name = "lillith/sauce"
version = "0.1.0"
description = "command framework"
authors = ["lillith"]
license = "MIT"

[target]
environment = "roblox"
build_files = ["src"]

[scripts]
roblox_sync_config_generator = ".pesde/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/sourcemap_generator.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"
